server:
  port: 8080

spring:
  datasource:
    hikari:
      connection-test-query: SELECT NOW() FROM dual
      connection-timeout: 30000
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      idle-timeout: 600000
      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:33061/hibernatedb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 1
      username: hibernatestudy
      password: hibernatestudy1234
  jpa:
    show-sql: true # SQL 쿼리 출력
    generate-ddl: true
    hibernate:
      # create의 경우 schema.sql, data.sql 둘 다 있을 경우 schema -> data 순으로 실행
      #
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리문을 눈이 보기 쉽게 출력
        highlight_sql: true
        use_sql_comments: false
    defer-datasource-initialization: true # gradle 2.5 이상 data.sql 파일의 스크립트는 Hibernate가 초기화 되기 전에 실행 Hibernate에 의해 생성된 스키마에 데이터를 추가하려면 true로 설정
  sql:
    init:
      mode: always  # classpath 경로의 sql 파일을 무조건 실행